# Generated by Django 3.0.7 on 2020-07-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_dailysummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='date',
            field=models.DateField(default='2020-07-10'),
            preserve_default=False,
        ),
    ]
