# Generated by Django 3.0.7 on 2020-07-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_dailysummary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysummary',
            name='stockEnd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='stockStart',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='totalIssued',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='totalReceived',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailysummary',
            name='totalReturned',
            field=models.IntegerField(default=0),
        ),
    ]
