# Generated by Django 3.0.7 on 2020-06-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
    ]
